/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cse.java.Login_Screen;

import cse.java.Class_Manager.ClassManaget_FirstPage;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author suk22
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Frametest
     */
    
    
    public Login_Page() {
        initComponents();
        setTitle("로그인");
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LOGIN_BUTT = new javax.swing.JButton();
        ID_INPUT = new javax.swing.JTextField();
        PW_INPUT = new javax.swing.JPasswordField();
        SHOW_PW = new javax.swing.JCheckBox();
        PW_CHANGE = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setText("대학 정보 시스템");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel2.setText("아이디");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel3.setText("비밀번호");

        LOGIN_BUTT.setText("로그인");
        LOGIN_BUTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BUTTActionPerformed(evt);
            }
        });

        ID_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_INPUTActionPerformed(evt);
            }
        });

        PW_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PW_INPUTActionPerformed(evt);
            }
        });

        SHOW_PW.setText("암호 가리기");
        SHOW_PW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_PWActionPerformed(evt);
            }
        });

        PW_CHANGE.setText("비밀번호 변경");
        PW_CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PW_CHANGEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SHOW_PW)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PW_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_INPUT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(LOGIN_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PW_CHANGE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ID_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PW_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SHOW_PW)
                .addGap(12, 12, 12)
                .addComponent(LOGIN_BUTT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PW_CHANGE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ID_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_INPUTActionPerformed

    private void LOGIN_BUTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BUTTActionPerformed
//        if(ID_INPUT.getText().equals("")){
//            JOptionPane.showMessageDialog(null,"로그인 실패하였습니다.");
//        }
//        else if(PW_INPUT.getText().equals("")){
//            JOptionPane.showMessageDialog(null,"로그인 실패하였습니다.");
//        }
//        else if(ID_INPUT.getText().contains("S001") && PW_INPUT.getText().contains("000000") ){ // 다음과 같은 입력을 받으면
//             JOptionPane.showMessageDialog(null,"로그인 성공했습니다."); // 로그인 성공
//        }
//        else{
//            JOptionPane.showMessageDialog(null,"로그인 실패하였습니다.");
//        }
        // 앞자리 문자 판별 후 학생,교수,학사담당자,수업담당자 화면 나타내기 P 교수, S 학생, H 학사 담당자, G 수업 담당자
        String fileName = "C:\\Users\\suk22\\Desktop\\login_test.txt"; // txt파일 위치
				//txt파일에 들어가는 내용은 아이디,비밀번호 로 입력해야함
        File file = new File(fileName);
        
        String ID = ID_INPUT.getText(); // 입력한 ID
        String PW = PW_INPUT.getText(); // 입력한 PW
        boolean check = false;
        boolean passwordcheck = false;
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                    String[] userInfo = line.split(","); // txt파일에 저장되어있는 아이디와 비밀번호를 나눠서 저장.
                    String storedID = userInfo[0]; // txt파일에 있는 ID
                    String storedPW = userInfo[1]; // txt파일에 있는 PW
                   
                    if(ID.startsWith(storedID)){
                        check = true;
                        if(PW.equals(storedPW)) {
                            passwordcheck = true;
                            break;
                        }
                    }
                    
                }
            }catch (IOException e) {
                e.printStackTrace();
            }   
        if(check && passwordcheck) {
            JOptionPane.showMessageDialog(null, "로그인에 성공했습니다."); // 로그인 성공
            
        char first_munja = ID_INPUT.getText().charAt(0); // 첫 번째 글자 판별 후 페이지 이동
        
        switch (first_munja) {
            case 'S': // 첫 번째 글자 S이면 학생 페이지로 이동
                Student_FirstPage St = new Student_FirstPage(); // 매개변수로 학생 정보 넘겨야 할 듯
                    St.setVisible(true);    
                    
                    setVisible(false); // 이전 창 안 보이게 함
                    break;
           
            case 'P': // 첫 번째 글자 P이면 교수 페이지로 이동
                    ClassManaget_FirstPage lcp = new ClassManaget_FirstPage(); // 매개변수로 정보 어떤 걸 어떻게?
                    lcp.setVisible(true);       
                    setVisible(false);
                    break;
                    
            case 'H': // 첫 번째 글자 H이면 학사 담당자 페이지로 이동
                    ClassManaget_FirstPage lcp = new ClassManaget_FirstPage(); // 매개변수
                    lcp.setVisible(true);       
                    setVisible(false);
                    break;        
                    
            case 'G': // 첫 번째 글자 G이면 수업 담당자 페이지로 이동
                    ClassManaget_FirstPage lcp = new ClassManaget_FirstPage(); // 매개변수
                    lcp.setVisible(true);       
                    setVisible(false);
                    break;
        }
        }else if(check){
            JOptionPane.showMessageDialog(null, "비밀번호가 일치하지 않습니다."); // 로그인 실패 -> 비밀번호 불일치
        }else {
            JOptionPane.showMessageDialog(null, "아이디가 일치하지 않습니다."); // 로그인 실패 -> 아이디 불일치
        }
        
        
    }//GEN-LAST:event_LOGIN_BUTTActionPerformed

    private void PW_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PW_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PW_INPUTActionPerformed

    private void SHOW_PWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_PWActionPerformed
       if(SHOW_PW.isSelected()){ // 암호 가리기
           PW_INPUT.setEchoChar((char)0);
       }
       else {
            PW_INPUT.setEchoChar(('*'));
       }
    }//GEN-LAST:event_SHOW_PWActionPerformed

    private void PW_CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PW_CHANGEActionPerformed
        
    }//GEN-LAST:event_PW_CHANGEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_INPUT;
    private javax.swing.JButton LOGIN_BUTT;
    private javax.swing.JButton PW_CHANGE;
    private javax.swing.JPasswordField PW_INPUT;
    private javax.swing.JCheckBox SHOW_PW;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
