/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cse.sms.view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 원채연
 */
public class GradeCheck extends javax.swing.JFrame {

    /**
     * Creates new form GradeCheck
     */
    public GradeCheck() {
        initComponents();
        setTitle("성적 확인");
        InputstdInfo();
        getSum();
    }

    private void InputstdInfo() {    //학생 수강 내역 파일에서 출력
        try {
            BufferedReader br = new BufferedReader(new FileReader("studentclasses.txt"));
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Object[] tableLines = br.lines().toArray();    //txt파일에서 몇줄인지 가져오기

            String inputStr[] = new String[4];
            for (Object tableLine : tableLines) {
                String line = tableLine.toString().trim(); //trim - 공백제거
                String[] dataRow = line.split(",");
                
                inputStr[0] = dataRow[2];    //강좌번호
                inputStr[1] = dataRow[3];    //강좌명
                inputStr[2] = dataRow[4];    //학점
                inputStr[3] = dataRow[8];    //성적
                        
                model.addRow(inputStr);
            }

        } catch (Exception ex) {
            ex.getStackTrace();
        }
    }

    private void getSum() {
        double sum = 0;
        String score;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            score = jTable1.getValueAt(i, 3).toString();
            switch (score) {
                case "A":
                    sum += 4.0;
                    break;
                case "B":
                    sum += 3.0;
                    break;
                case "C":
                    sum += 2.0;
                    break;
                case "D":
                    sum += 1.0;
                    break;

                case "F":
                    sum += 0;
                default:
                    break;

            }
        }
        
        sum = (sum / jTable1.getRowCount());
        String result = String.format("%.2f", sum);
        jTextField1.setText(result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "강좌번호", "강의명", "학점수", "성적"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jTextField1.setText("jTextField1");

        jLabel1.setText("평균 학점");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
