/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cse.sms.view;

import cse.sms.control.UserData;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import java.io.BufferedWriter;

/**
 *
 * @author 915
 */
public class PWChange extends javax.swing.JFrame {
    
    UserData loginUser = UserData.getInstance();
    
    /**
     * Creates new form PWChange
     */
    public PWChange() {
        initComponents();
        setTitle("비밀번호 변경 " + loginUser.getID() + loginUser.getName());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentPasswordTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newPasswordTextField = new javax.swing.JTextField();
        confirmNewPasswordTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("현재 비밀번호");

        jLabel2.setText("새 비밀번호");

        jLabel3.setText("새 비밀번호 확인");

        jButton1.setText("확인");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("뒤로 가기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmNewPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(newPasswordTextField)
                        .addComponent(currentPasswordTextField)))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmNewPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 누구인지 판별해서 읽을 파일 정하기
        char firstChar = loginUser.getID().charAt(0);
        
        String filename = null;
        
        switch(firstChar) {
            case 'S':
                filename = "studentInfo.txt";
                break;
            case 'P':
                filename = "professorInfo.txt";
                break;
            case 'G':
                filename = "classmanagerInfo.txt";
                break;
            case 'H':
                filename = "schoolmanagerInfo.txt";
                break;
        }
       
            String currentPassword = currentPasswordTextField.getText(); //현재 비번
            String newPassword = newPasswordTextField.getText(); // 새 비번
            String confirmNewPassword = confirmNewPasswordTextField.getText(); // 새 비번 확인
            
            // 현재 비번, 새 비번, 새 비번 확인이 모두 일치하는지 확인
        if (!(currentPassword.isEmpty() || newPassword.isEmpty() || confirmNewPassword.isEmpty())) {
            if (currentPassword.equals(loginUser.getPW()) && newPassword.equals(confirmNewPassword)) {
                // BufferedReader를 사용하여 파일을 읽어 아이디를 비교하여 비밀번호를 변경
                List<String> lines = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(filename), "UTF-8"))){
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] data = line.split(",");
                        String savedID = data[0];
                        String savedPassword = data[1];
                        
                        if (loginUser.getID().equals(savedID)) {
                            data[1] = newPassword; // 새로운 비밀번호로 변경
                        }
                        lines.add(String.join(",", data)); // 변경된 데이터를 리스트에 추가
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
                
                // 새 비밀번호를 파일에 저장
                
                try {
                    BufferedWriter writer = new BufferedWriter(new FileWriter(filename));
                    for (String line : lines) {
                        writer.write(line);
                        writer.newLine();
                    }
                    writer.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                
                JOptionPane.showMessageDialog(this, "비밀번호가 성공적으로 변경되었습니다.");
                switch (firstChar) {
                    case 'S':
                        dispose();
                        ST_FirstPage st = new ST_FirstPage();
                        st.setVisible(true);
                        break;
                    case 'P':
                        dispose();
                        PF_FirstPage pf = new PF_FirstPage();
                        pf.setVisible(true);
                        break;
                    case 'G':
                        dispose();
                        CM_FirstPage cm = new CM_FirstPage();
                        cm.setVisible(true);
                        break;
                    case 'H':
                        dispose();
                        SM_FirstPage sm = new SM_FirstPage();
                        sm.setVisible(true);
                        break;
                }
            } else {
                JOptionPane.showMessageDialog(this, "비밀번호 변경에 실패했습니다. 입력한 정보를 다시 확인해주세요.");
            }
        }else {
            JOptionPane.showMessageDialog(this, "빈칸이 없도록 입력해주세요.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        char firstChar = loginUser.getID().charAt(0);
        switch(firstChar) {
            case 'S':
                dispose();
                ST_FirstPage st = new ST_FirstPage();
                st.setVisible(true);
                break;
            case 'P':
                dispose();
                PF_FirstPage pf= new PF_FirstPage();
                pf.setVisible(true);
                break;
            case 'G':
                dispose();
                CM_FirstPage cm = new CM_FirstPage();
                cm.setVisible(true);
                break;
            case 'H':
                dispose();
                SM_FirstPage sm = new SM_FirstPage();
                sm.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmNewPasswordTextField;
    private javax.swing.JTextField currentPasswordTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField newPasswordTextField;
    // End of variables declaration//GEN-END:variables
}
